const guardian = createGuardian('Guardian');
// guardian.canMove();
// guardian.defend();
// const wizard = createWizard('Wizard');
// wizard.canMove();
// wizard.castSpell();
// const warior = createWarior('Warior');
// warior.canMove();
// warior.attack();
// warior.defend();